### ISSUE TITLE
ENH Save the loss at the initial point

### ISSUE THREAD

**Issue by ngazagna** [benchopt/benchopt#100]
When implementing stochastic methods, I realized that the first point at which the loss is computed is $w^1$ and not $w^0$. 

By modifying this all the curves will start from the same point, which makes more sense

**Comment by ngazagna** [comment]
To be linked to https://github.com/benchopt/benchOpt/pull/123

**Comment by mathurinm** [comment]
normally, this is done now since we start `n_iter` at 0. Feel free to reopen if you still see the problem @ngazagna
