### ISSUE TITLE
ENH Add a requirements.txt for each benchmark

### ISSUE THREAD

**Issue by ngazagna** [benchopt/benchOpt#102]
I wanted to test the lasso benchmark and I had to install manually each solver (`cyanure`, `celer`, `lightning` etc). I guess we could try to write a `requirements.txt` to install all these solvers directly.

**Comment by tomMoral** [comment]
I don't think this is a good idea as the info is already in each solver with the `requirements`. Duplicating this info will lead to increase maintenance cost.

I think it would be good however to have a sub command in `benchopt` to install the dependencies in the current environment. or to generate a `requirement.txt` if you prefer.

**Comment by ngazagna** [comment]
I don't know what's preferable between generating `requirements.txt` and a `benchopt` sub command. I guess that running something like
```bash
benchopt run ./path/to/benchmarks/lasso --install-dependencies
```
could be great since the requirements are related to a specific benchmark.

Also, since we are allowing R and Julia solvers, these also leads the user to install manually some packages like I did this morning for `glmnet` in R: 
```python
from rpy2.robjects.packages import importr
utils = importr('utils')
utils.install_packages('glmnet')
```
