### ISSUE TITLE
cannot run benchmark

### ISSUE THREAD

**Issue by jmairal** [benchopt/benchOpt#107]
Hi,

on two different machines running two different variants of anaconda
   pip install benchopt
   git clone https://github.com/benchopt/benchmark_lasso
   benchopt run ./benchmark_lasso

results in 
******************
    from benchopt import BaseDataset
ImportError: cannot import name 'BaseDataset' from 'benchopt' (/opt/miniconda3/lib/python3.7/site-packages/benchopt/__init__.py)
******************

**Comment by tomMoral** [comment]
Hi,

Yes sorry about that, we are releasing a new version of `benchopt` and the benchmarks do not work with the old version...
We will release it before 1 or 2 days.
To make this work, could you install `benchopt` from the master branch?
```bash
git clone https://github.com/benchopt/benchopt
pip install -e ./benchopt
git clone https://github.com/benchopt/benchmark_lasso
benchopt run ./benchmark_lasso
```

This is definitely an issue we should consider, how do we pin the benchmark to a given version of `benchopt` so we don't break everything when we develop new features. Not sure we have a proper solution right now.

**Comment by jmairal** [comment]
Thanks!

**Comment by tomMoral** [comment]
Just realized that another thing that might not work is the auto install.
To run with the auto-install on master, you need to call:
```bash
benchopt run --env ./benchmark_lasso
```

Else, only solvers that are already installed will work. We need to update the documentation.

**Comment by jmairal** [comment]
Not there yet

Installing Blitz in None:... failed                                                                                                                                                                                                                                            
Installing cd in None:... failed                                                                                                                                                                                                                                               
Installing Celer in None:... failed                                                                                                                                                                                                                                            
Installing cvxpy in None:... failed                                                                                                                                                                                                                                            
Installing glmnet in None:... failed                                                                                                                                                                                                                                           
Installing Julia-PGD in None:... failed                                                                                                                                                                                                                                        
Installing Lightning in None:... failed                                                                                                                                                                                                                                        
Installing R-PGD in None:... failed                                                                                                                                                                                                                                            
Installing statsmodels in None:... failed                                                                                                                                                                                                                                      
/tmp/tmpx1u37oo3: ligne 2: benchopt.benchmark.Benchmark: Aucun fichier ou dossier de ce type

**Comment by agramfort** [comment]
with master branches on all repos it works for me

**Comment by jmairal** [comment]
benchopt run --env ./benchmark_lasso  seems to do the trick (still waiting Creating conda env benchopt_benchmark_lasso:... to complete)

**Comment by jmairal** [comment]
Still having issues 
/tmp/tmppyy27t24: line 4: benchopt.benchmark.Benchmark: No such file or directory

**Comment by agramfort** [comment]
if you run the benchmark with -l to use your local environment?

benchopt run ./benchmark_lasso -s cyanure -d boston -l

for example

>

**Comment by jmairal** [comment]
This works.

**Comment by jmairal** [comment]
last update. I get the .csv but not the plot

Traceback (most recent call last):
  File "/opt/miniconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/cli.py", line 107, in run
    timeout=timeout, plot_result=not no_plot, pdb=pdb
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/runner.py", line 391, in run_benchmark
    plot_benchmark(df, benchmark)
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/viz/__init__.py", line 46, in plot_benchmark
    output_dir = _get_output_folder(benchmark)
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/utils/files.py", line 5, in _get_output_folder
    output_dir = Path(benchmark) / "outputs"
  File "/opt/miniconda3/lib/python3.7/pathlib.py", line 1022, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/miniconda3/lib/python3.7/pathlib.py", line 669, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/miniconda3/lib/python3.7/pathlib.py", line 653, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not Benchmark

**Comment by tomMoral** [comment]
We had a bug for the `--env` option. This should be fixed in #108.

For the plotting utils, this is also a bug due to a too hasty refactoring, this should be fixed by (unrelated) #105 .
Hopefuly we merge all this quickly

**Comment by tomMoral** [comment]
Ok I merged the 2 fixes.
So if you pull master, it should now work.

Note that you need to install `pygithub` which is a new dependency for the package (to publish the benchmark results).

**Comment by jmairal** [comment]
That would be great. We are probably going to send you a few pull requests for Cyanure in a near future (a new engineer has just joined our team and will work on this project, since I have had zero time since last march to do any update).
For instance, right now, the objective function in .csv has nothing to do with the one displayed by Cyanure with the verbose option "-v" and I would like to know why. But I am digressing:

- I tried the above commandes (using -env), after doing the right git pull etc...
and I got

AttributeError: module 'benchopt' has no attribute '__version'

**Comment by tomMoral** [comment]
When it does not want to work :sweat: 
This is a weird one here.

Just to be on the safe side, could you try to call this once with `--env` and `--recreate`. This will recreate the env `benchopt_benchmark_lasso` and reinstall everything. Sometime there can ba a discrepancy between the version installed in the conda env and the local one.

**Comment by tomMoral** [comment]
It the env is indeed `benchopt_benchmark_lasso`, you can also activate it and make sure that the correct version of benchopt is running manually if you don't want to recreate the env (which can be slow).

**Comment by jmairal** [comment]
That works. Let me close the topic.

**Comment by tomMoral** [comment]
Thanks a lot for coping with all the bugs and following up with us @jmairal !
Hope you find it useful, let us know where you see room for improvment :)

**Comment by agramfort** [comment]
@jmairal FYI
https://benchopt.github.io/results/benchmark_lasso_benchopt_run_2020-12-16_14h59m11.html
this is where we are at this point

>
