### ISSUE TITLE
Issue with conda env creation in run

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchopt#119]
Hi,

I am trying to run the benchmark with a conda env.
I am running it the following way: `benchopt run --env ./`.
I installed `benchopt` from source (with the latest version).
My conda version is `4.5.12` (just tried with an updated `4.9.2` and it's the same story), and Python is `3.6.8`.
The error I get is:

```
Creating conda env benchopt_benchmark_lasso:... failed to create the environment.
Traceback (most recent call last):
  File "/home/zaccharie/workspace/benchmark_lasso/venv/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zaccharie/workspace/benchmark_lasso/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zaccharie/workspace/benchOpt/benchopt/cli.py", line 115, in run
    create_conda_env(env_name, recreate=recreate)
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/shell_cmd.py", line 184, in create_conda_env
    capture_stdout=True, raise_on_error=True
  File "/home/zaccharie/workspace/benchOpt/benchopt/utils/shell_cmd.py", line 93, in _run_shell
    raise RuntimeError(raise_on_error.format(output=output))
RuntimeError: /tmp/tmpn6mny88h:2: command not found: conda
```

When I turn on the debugging flag (`BENCHO_DEBUG=True`), I find that the env creation is done with the following command `conda env create  -n benchopt_benchmark_lasso -f /tmp/conda_env_7xfo9azm.yml`.

When I run this command on its own, I find the following error:
```
SpecNotFound: Invalid name, try the format: user/package
```

This error has been described [here](https://github.com/conda/conda/issues/3859) as well, and apparently it carries on until today. 
I tried to fix it by simply removing the `env` in the command in [this line](https://github.com/benchopt/benchOpt/blob/master/benchopt/utils/shell_cmd.py#L183), but I still get the same error (i.e. `RuntimeError: /tmp/tmpn6mny88h:2: command not found: conda`).

For further investigation, I added a breakpoint [here](https://github.com/benchopt/benchOpt/blob/master/benchopt/utils/shell_cmd.py#L86), and saw that the command being run was in a tmp file, in this instance `/usr/bin/zsh /tmp/tmp1dwabbzo`.

When using this command in a different shell (with the tmp file being still present), I get the following error:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - /tmp/conda_env_kwp39_w4.yml

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I can see how it's not the same as `command not found: conda`. But I have no idea on how to debug further than this because the command run in the terminal or the command run in the `subprocess.getstatusoutput` do not give the same results...

For info the content of `/tmp/tmp1dwabbzo` is:
```
set -e
conda create  -n benchopt_benchmark_lasso -f /tmp/conda_env_kwp39_w4.yml
```

**Comment by mathurinm** [comment]
Is it possible that :
- `conda env create` should not be used (`conda create` instead)
- `conda create` failed because one of the packages (julia, R ?) needed to be installed through conda-forge, which is not listed in the channels in your error message ?

**Comment by zaccharieramzi** [comment]
Closing this, as the new error is now: https://github.com/benchopt/benchopt/issues/307
