### ISSUE TITLE
ENH : adding bibtex / references to credit solvers

### ISSUE THREAD

**Issue by josephsalmon** [benchopt/benchopt#120]
That would be great to have a uniform way of crediting the papers / solvers added to the various benchmarks.
For the moment, no credit is given (except may be the github where some sources might be coming from).

Bibtex of the papers might be reasonable start.

Any thought on the way to proceed @agramfort ?

**Comment by agramfort** [comment]
I would go with either the dumb solution :

- add a bibtex class attribute to each solver

or (maybe) use a fancy solution like:

- https://github.com/duecredit/duecredit

not sure it's worth it though as it adds quite some dependencies

**Comment by mathurinm** [comment]
@josephsalmon this can go in the solver's docstring, which is displayed on the HTML page:
 
![image](https://github.com/benchopt/benchopt/assets/8993218/a261eb4f-8f2c-46ad-81a0-933afba8916d)

if you find it satisfying I'll let you close the issue

**Comment by josephsalmon** [comment]
That's lovely. Thanks for this solution.
