### ISSUE TITLE
DOC : Write on the website what are the plot kinds available

### ISSUE THREAD

**Issue by ngazagna** [benchopt/benchOpt#124]
On : 
https://benchopt.github.io/cli.html#benchopt-plot
user don't know what they can write as `<kinds>`.

**Comment by ngazagna** [comment]
1. `suboptimality_curve`
2. `relative_suboptimality_curve`
3. `objective_curve`
4. `histogram`

**Comment by agramfort** [comment]
it even looks very wrong. It says:

Timeout a solver when run for more than <timeout> seconds
PR welcome !

>

**Comment by agramfort** [comment]
@ngazagna the lines you need to fix in your PR are https://github.com/benchopt/benchOpt/blob/master/benchopt/cli.py#L155

thanks for your help !

**Comment by ngazagna** [comment]
> PR welcome !
Done in 
https://github.com/benchopt/benchOpt/pull/129
