### ISSUE TITLE
PyTorch based opt library ?

### ISSUE THREAD

**Issue by GeoffNN** [benchopt/benchopt#141]
Hi everyone,

I've been working on an [optimization library based on PyTorch](https://github.com/openopt/chop). 
Everything in it may not directly fit current `benchopt` benchmarks, but I'd be glad to help integrate it.
Let me know if you're interested!

**Comment by agramfort** [comment]
hi @GeoffNN !

to integrate chop you would just need to touch the benchmarks not the benchopt code (ideally)

see https://github.com/benchopt/benchmark_logreg_l2/pull/11 for how I added copt to the l2 logreg benchmark.

here is an example I got using my PR:

https://benchopt.github.io/results/benchmark_logreg_l2_benchopt_run_2021-03-06_13h48m00.html

looking forward to working with you on this

**Comment by GeoffNN** [comment]
Just submitted a PR based on yours in the logreg_l2 repo!

**Comment by tomMoral** [comment]
Closing this issue as this has been done in the proper repo! Thx @GeoffNN
