### ISSUE TITLE
ENH : maybe we need to copy X and y  in every solver

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#187]
With @pabannier we ended up having a nasty bug because one solver scaled X inplace and then all solvers failed to converge. 

If a `solver` instance is deleted before the next `solver` is instanciated, this should not be a memory issue to have one copy of X per solver (i.e. we don't have `n_solvers` simultaneous copies of the same `X`)

In our case the behavior was really nasty, I don't know if it's worth copying always, but anyways I find it worth sharing

**Comment by agramfort** [comment]
You should flags the data arrays as read only so you will be safe.

**Comment by mathurinm** [comment]
sklearn's and celer's cython break if do this
