### ISSUE TITLE
some solvers run for a long time and make the plot upper xlimit too large

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#188]
eg 
![image](https://user-images.githubusercontent.com/8993218/126457585-9c822c63-04f7-467f-8995-c483e05ae067.png)

should this be addressed at the solver/bench level, or at the plot level ?

**Comment by agramfort** [comment]
can you zoom in the plotly figure?

**Comment by mathurinm** [comment]
I have the possibility to do so, but I'm lazy (as the average user) and would like it done automatically :)

**Comment by agramfort** [comment]
Fair enough…

**Comment by mathurinm** [comment]
It seems to happen for some solvers, but not for all:
![image](https://user-images.githubusercontent.com/8993218/136036651-43427112-f47b-4749-9f03-5b08a8e34d14.png)

**Comment by mathurinm** [comment]
@tomMoral clarified this behavior: we stop increasing the solver iteration/decreasing its tolerance after 3 iterations where the objective decrease is less than 1e-10 (`benchopt.stopping_criterion.PATIENCE` and `benchopt.stopping_criterion.EPS`)

For super fast solvers (eg anderson above), the points accumulate at the last point, but they are nevertheless here)

**Comment by mathurinm** [comment]
@tanglef suggested that we could remove the 3 last points from plotting (but we would need to check that they were 3 points without progress, and not the solver running up to max_runs)

**Comment by tomMoral** [comment]
When we construct the curve, we could probably store the information ('converged').
This way we could also add an option to only display 'converged' solvers and remove the last 3 points when necessary.
