### ISSUE TITLE
xlim does not seems to always be updated when solvers are selected/deselected

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#189]
Sometimes unticking a solver changes the x axis, sometimes it does not (e.g:
![image](https://user-images.githubusercontent.com/8993218/126459418-d1f46a14-4ecf-4ffd-918b-49aadf21d096.png)

reproduce:: select the first config in the following report, tick and untick PGD: xlim changes. removing more solvers does not reduce the xlim.

https://www.dropbox.com/s/kicnhajwt3jwgov/benchmark_bcd_benchopt_run_2021-07-21_10h25m04.html?dl=0

**Comment by tanglef** [comment]
Plotly actually  does its job. It rescales the axis when we deselect one curve or more.
It rescales up to the next trace it encounters.
And here the problem is that, the next trace is the horizontal black dotted line.

**Comment by mathurinm** [comment]
fixed by #191
