### ISSUE TITLE
ENH: be able to set arbitrary values of solver/dataset/objective parameters via CLI

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#193]
I think it would be nice to be able to do `benchopt run . -d simulated[n_samples=30,n_features=50]` even if `simulated.py` does not have the values, 30 and 50, as long as `n_samples` and `n_features` are keys of `Dataset.parameters` 

all unspecified parameters would take all their default values

**Comment by mathurinm** [comment]
The more I use it, the more I want to be able to do it. 
I think we should think of arguments between brackets as python keyword args:
- their positions in the bracket should not matter - currently, they do: 
![image](https://user-images.githubusercontent.com/8993218/140475244-966be18b-c675-44a7-96f5-f1b27dd7eef5.png)

- if they are not specified, all default values specified in the `.py` should be taken (a bit different than Python behavior, but corresponds to what we want)
- you can set a value that is not present in the default list of values, without having to rewrite the `.py`




Expected behaviour, with these parameters for `Simulated`: 
```python
    parameters = {
        'n_samples': [500, 1000],
        'n_features': [2000, 4000],
        'rho': [0.6],
    }
 ```
 
-  `-d simulated` runs all combinations, as it does now
- `-d simulated[n_samples=500] `  runs 2 configs: (500, 2000, 0.6) and (500, 4000, 0.6)
- `-d simulated[n_samples=2000] `  runs 2 configs: (2000, 2000, 0.6) and (2000, 4000, 0.6)   (currently not supported)
- `-d simulated[n_features=2000,n_samples=500]` is supported (currently not)

**Comment by agramfort** [comment]
PR welcome :)

**Comment by mathurinm** [comment]
i think this first deserves a discussion with @tomMoral as it would modify in depth the process :)

**Comment by mathurinm** [comment]
Another solution to easily add new parameter values to solvers/datasets without changing the python files (which breaks  Memory.cache) is to go through config files. Both solutions seem to cover different cases and should be worth implementing
