### ISSUE TITLE
ENH simulated dataset has nearly diagonal covariance

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#21]
I understand that's it a toy dataset, but we could introduce a bit of correlation in the data: the solvers run in < 0.01 s and the results are not trustable. I wouldn't mind per se, if it weren't the first figure that people were shown. Additionally I wouldn't accept such a dataset in a paper I review.

We can easily construct a Toeplitz 2d array without scipy (corr_{ij} = rho ** |i - j|) and use it as covariance when generating data. Afterwards, if one wants, rho could be made a parameter of the dataset.

What is your take on this @tomMoral @agramfort ?

**Comment by agramfort** [comment]
+1 to add toeplitz designs in simulations

>

**Comment by tomMoral** [comment]
+1

**Comment by tomMoral** [comment]
Done in #24
