### ISSUE TITLE
ENH/BUG: choose solver colors on a wider range

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#213]
For 4 solvers we already have 2 red ones:
![image](https://user-images.githubusercontent.com/8993218/136019788-c2624548-27da-4e47-97d8-8add7ff61b6b.png)

I don't understand why this happens. When we pick the color we use CMAP(i): https://github.com/benchopt/benchOpt/blob/master/benchopt/plotting/plot_objective_curve.py#L84

If I show this palette outside of benchopt, it looks good and colors 3 and 4 are orange, not red. 
![image](https://user-images.githubusercontent.com/8993218/136020258-ff2d139a-4ee5-487d-9b9b-05f002bb4dc2.png)

**Comment by josephsalmon** [comment]
you use 
`CMAP = plt.get_cmap('tab20')`
https://github.com/benchopt/benchOpt/blob/090bf974b5d2357e8d83771ec2d950c79ebb1ff1/benchopt/plotting/plot_objective_curve.py#L7

Seems it is not defined for plotly, right?

**Comment by mathurinm** [comment]
you use this line to do `color=CMAP(i)`  which  returns a 4-uplet that is passed as `color` to plotly in fill_between_x
