### ISSUE TITLE
ENH/PLT: add way to toggle shaded areas on and off

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#228]
Sometimes I use `-r 10` to get less bumpy curves, but it may get hard to read with the shaded areas and it could be nice to disable them. It's not a critical feature, but if it's easy to do then WDYT ?
![image](https://user-images.githubusercontent.com/8993218/140294502-91d7eca0-a30a-4297-b069-86e5a8772880.png)

**Comment by tomMoral** [comment]
Seems a fun feature. Add it if you want (I guess this is again some plotly JS stuff)
