### ISSUE TITLE
ENH: add a way to delete benchmarks results from html page ?

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#229]
I tend to have quite many outputs in the end, maybe we could have a `trash` icon on every line  in the right most column that would delete them and the associated csv (after prompting for confirmation) ?
![image](https://user-images.githubusercontent.com/8993218/140473498-b152a475-f816-48ed-bd61-7a087a174cd2.png)

Also, when I delete the benchmarks manually (html and csv), they still appear on `lasso.html`.

**Comment by tanglef** [comment]
It would be available only for user-local rendering right?
We don't want anyone to be hable to delete files from the website (and authentification access to check if the person in an admin in static websites isn't really a thing)

**Comment by mathurinm** [comment]
Yes, I'm biased as my use is only local

**Comment by tanglef** [comment]
And for the fact that deleted html files still appear in the `lasso.html`: do you mean after a refresh only or after regenerating the website? Because with the former it is the expected behavior, if you delete the html page the table was still already generated with mako (and the design is static).

**Comment by agramfort** [comment]
just remove the file in the results repo and the website will remove the benchmark automatically with the CI

**Comment by agramfort** [comment]
as admin I can delete a .csv file from github.com

otherwise you can open a PR to delete a file from github.com in a few clicks

>

**Comment by mathurinm** [comment]
I'm using benchopt locally to produce figures for an article, not to publish a benchmark online

**Comment by tomMoral** [comment]
I agree that would be nice for local files but this would require a server I guess 😅 
We only have static pages so I don't see how we could delete files (and I would be worried if JS allowed us to do so).

Does anyone has an idea on how we could have such features?

**Comment by agramfort** [comment]
just remove the .csv on github

I've done it many times already to cleanup my mess

>

**Comment by tomMoral** [comment]
This is not the point @agramfort :)
We are talking about local files.

**Comment by agramfort** [comment]
how about "rm" then :)

**Comment by tanglef** [comment]
rm is good, but a UI is always nicer to work with IMO, you could more easily see what bench you are deleting

**Comment by tomMoral** [comment]
Yes indeed, this works. Question is, can we make something easier to manage a lot of result files?
Honestly I am not sure.

**Comment by tanglef** [comment]
Is it okay if we split it into two sequential problems:
- allow a `--server/--no-server` flag on `benchmark plot` that will generate a local server rendering the page with the benchs table,
- in JS, if `location.hostname === "127.0.0.1"` then display the trash icon and play with ajax requests and php as we wish to break out of the JS sandbox security.
The first is easy, I can take care of it. The second I have no notion of php for now :sweat_smile:

**Comment by tomMoral** [comment]
I think this is a lot of work for a small gain so I would say don't bother.
Moreover, it will be hard to test/maintain.

A simpler solution maybe: add a checkbox and an area with the list of path for all files that are checked?
So that way one can just copy/paste the `rm` command?
