### ISSUE TITLE
PLT: for some objectives, suboptimality, relative suboptimality etc do not make sense

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#239]
For example, monitoring sparsity of the iterates for the Lasso, I can't envision a case where one wants to use relative suboptimality.
I can't see an obvious solution right now.

**Comment by mathurinm** [comment]
would it make sense to propose suboptimality/relative suboptimality only for `value` ?

**Comment by agramfort** [comment]
You can have test and train losses.  would you want suboptimality for test
loss?

>

**Comment by mathurinm** [comment]
I think not, I've never seen in a paper : for the test loss F(x^*) depends on the solvers being added to the graph.

So, for me it makes more sense to propose subopt only for `value`, the objective actually being minimized.

**Comment by agramfort** [comment]
let's do this then

>

**Comment by tomMoral** [comment]
I disagree, this is only for your particular use case. Adding this restriction won't improve the lib and might hinder some use cas.
I don't see why we should restrict this type of plots, if they don't make sense, don't look at it :)

I would say in the long run, we can add some meta data to make sure we only plot what make sense but this is a longer term goal. So I would keep it that way for now.

**Comment by mathurinm** [comment]
We can discuss solutions around coffee but having 16 matplotlib figures showing up as the result of our default `plot_run_benchmark` really bothers me (indeed this is my particular usecase)

**Comment by mathurinm** [comment]
Another example : this plot in the doc is wrong: 
https://benchopt.github.io/_images/sphx_glr_plot_run_benchmark_python_R_julia_005.png

F(x*) is read as F at optimum, while it is in fact min_F, F being || . ||_0, thus 0 here.

**Comment by mathurinm** [comment]
One more reason to talk about it: `benchopt run ./benchmark_lasso -s sklearn -s celer -d simulated --no-html -r1` opens **288 figures**. 
At this point I would like to not look at them, but is not possible with matplotlib (with plotly I agree)
