### ISSUE TITLE
Use the quiet flag for install_in_conda_env instead of DEBUG?

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#253]
Here: https://github.com/benchopt/benchOpt/blob/master/benchopt/utils/conda_env_cmd.py#L197

From the issue https://github.com/benchopt/benchmark_lasso/issues/14, it would be useful to also be verbose in the pip install steps.

We can currently, by setting BENCHOPT_DEBUG, but I would expect to be full verbose if one does not use `--quiet`, especially since the whole list of pacakges to be installed is displayed at once so you don't know which install is taking time.

WDYT of replacing `not DEBUG` by `quiet` here @tomMoral ?

**Comment by tomMoral** [comment]
I agree, I actually thought you did it in the previous PR. :sweat_smile: 
As the install step is separate, we should show as much as possible what is going on.

**Comment by mathurinm** [comment]
implemented in #254
