### ISSUE TITLE
API benchopt install . -s somesolver should not install all datasets

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#257]
for benchmark running, the current behavior (specifying no dataset means all) is nice

bur for installation, I think if no -d flag is supplied, no dataset should be installed. If I want to install a single solver I don't want to install all datasets at the same time

**Comment by agramfort** [comment]
And then to install datasets I need to install each one manually ? Could be have a Boolean if we want to install only solvers ?

**Comment by mathurinm** [comment]
`-d '*'`

**Comment by agramfort** [comment]
would

benchopt install . --no-data

fix your usecase? this would ignore the datasets

>

**Comment by tomMoral** [comment]
I would say, as soon as one of `-d` or `-s` is specified, we should not install anything else by default.
So `benchopy install . -s celer` simply install `celer`, `benchopt install . -d boston` simply install `scikit-learn` and `benchopt install .` install everything?

**Comment by tomMoral** [comment]
+ we could have `-d all` and `-s all` for shortcut?

**Comment by agramfort** [comment]
> So benchopy install . -s celer simply install celer, benchopt install . -d boston simply install scikit-learn and benchopt install . install everything?

that would work for me.

**Comment by tomMoral** [comment]
Fixed in #268
