### ISSUE TITLE
BUG DOC search is not working on the doc website

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#271]
At least on my side: it gets suck with "Searching ...":
![image](https://user-images.githubusercontent.com/8993218/146184361-7b745b19-fb3e-4549-b456-d63ce25250e9.png)

https://benchopt.github.io/search.html?q=autocompletion&check_keywords=yes&area=default

**Comment by tanglef** [comment]
Would a temporary fix replicating [this PR](https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/213) be all right?
For an example of the modification that implies (a new html file) see [the branch I created for that](https://github.com/tanglef/benchOpt/tree/search_bar)

**Comment by mathurinm** [comment]
Yes I would be OK with it, I think Eric knows what he's doing :100:  
@agramfort do you approve ? @tanglef can you launch a PR ?

**Comment by agramfort** [comment]
yes go for it
