### ISSUE TITLE
What's the best way to share code without making it a module?

### ISSUE THREAD

**Issue by PABannier** [benchopt/benchopt#279]
I'd like to reuse pieces of my code (say `get_alpha_max` for the Lasso) which I've put in a `utils.py` file inside a module that I install by running `pip install -e . `. 

Is there a better way to share code in a same bench without creating a module?

**Comment by tomMoral** [comment]
I agree that this is something that we should fix. I might have a solution that would allow something like:

```python
from benchopt import safe_import_context

with safe_import_context() as import_ctx:
    utils = import_ctx.import('utils.py')
```

Would that address your use case?

**Comment by tomMoral** [comment]
A big question is how to distinguish these files from the `solvers/datasets` files.
A possibility would be to put them in a separate `utils` module in the benchmark, so the file tree would be:
```
benchmark_dir
|- objective.py
|- solvers
|- datasets
|- utils
|--- alpha_max.py
|--- ....
```

and the import would go through
```python
from benchopt import safe_import_context

with safe_import_context() as import_ctx:
    alpha_max = import_ctx.import_from('alpha_max.py')
    get_alpha_max = import_ctx.import_from('alpha_max.py', 'get_alpha_max')
```

WDYT?

**Comment by PABannier** [comment]
Yes I think it is cleaner. Right now, I have a utils folder with a `setup.py` in the same directory as `solvers`, `datasets` and `objective.py`. I'll try the solution you describe and let you know.

**Comment by tomMoral** [comment]
@PABannier If you can try the code from #286 for your use case, that would be super helpful!

**Comment by PABannier** [comment]
@tomMoral I just tried your code. It works like a charm for me :)

**Comment by PABannier** [comment]
@tomMoral I think it is very helpful as it cleans up the benchmark folder by removing one package directory, one `setup.py` file and other automatically generated files.

**Comment by zaccharieramzi** [comment]
Works for me as well, I just want to highlight that one should not add `.py` at the end of the import unlike the example [here](https://github.com/benchopt/benchopt/issues/279#issuecomment-1006395887).

**Comment by tomMoral** [comment]
Nice, I fixed the example.

Do you guys see any good ways of improving this API?
Else, I think we should better document this feature in the doc.

**Comment by zaccharieramzi** [comment]
Nothing comes to mind immediately, but yes having it featured in the "Write a benchmark" doc would be interesting as well as the template repo.
