### ISSUE TITLE
ENH: ctrl-C takes >10s to kill benchopt when the figures are showing 

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#30]

**Comment by agramfort** [comment]
it's not a benchopt pb.

>

**Comment by agramfort** [comment]
i use then:

ctrl+z
kill %

>

**Comment by mathurinm** [comment]
where does the problem come from ?

**Comment by agramfort** [comment]
closing matplotlib process I guess. I see the same issue with mne examples
that open many plots

>

**Comment by tomMoral** [comment]
It is because the terminal does not have the focus anymore.
The `matplotlib` windows close when you focus on them so doing `Ctrl+C` then going to `matplotlib` plot usually do the trick.

But it is true that it would be nice to have some way to close all windows at once in `benchopt`.

**Comment by mathurinm** [comment]
I can't reproduce, now it closes in ~1 s
