### ISSUE TITLE
[Feature request] Possibility to factorize elements between solvers

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchopt#308]
It might be possible to do already, but I don't know through which mechanism.

I would basically like to factorize some code between different solvers, for example using an intermediate base class inheriting `BaseSolver`.
But I don't how I could then import this intermediate class in my solvers.

Any clue how to do this?

At the time being I can of course just have some not very DRY code.

**Comment by tomMoral** [comment]
This has not been documented yet but we have an API to factorize code in a benchmark that have been implemented in this PR: https://github.com/benchopt/benchopt/pull/286

could you take a look and report if this fixes your issue?

**Comment by zaccharieramzi** [comment]
I agree this is a duplicate with #279
