### ISSUE TITLE
Capture stdout of C or FORTRAN solvers

### ISSUE THREAD

**Issue by TomDLT** [benchopt/benchOpt#31]
As described in https://github.com/benchopt/benchOpt/pull/25#issuecomment-604082555, we might want to capture stdout of C or FORTRAN solvers, which is not straightforwardly doable with `contextlib.redirect_stdout`, but something like [this solution](https://stackoverflow.com/a/29834357/6156647) works.

I wonder if this is something worth adding to benchopt, since it might be useful for multiple solvers, including `benchmarks/nnls/solvers/nnls_scipy.py`.

**Comment by tomMoral** [comment]
The [solution above](https://stackoverflow.com/a/57677370/2642845) seems a simpler candidate no? It does not handle threaded stream and  capture but if we just want to suppress the stdout, it does the job?

**Comment by tomMoral** [comment]
I did a utility context for this in this file: https://github.com/benchopt/benchOpt/pull/51/files#diff-65ee127968665794e19f1abc7bc26fac
It could be used to capture the output for FORTRAN solvers.

**Comment by TomDLT** [comment]
Tested in #53, works well !
