### ISSUE TITLE
Plotting bug: quantiles button ignores plotly selected curves when toggled

### ISSUE THREAD

**Issue by TomDLT** [benchopt/benchopt#317]
If I select one curve with plotly, and then toggle the "quantiles" button, it shows the quantiles of all curves, instead of only plotting the quantiles of selected curves. 
![image](https://user-images.githubusercontent.com/11065596/160949519-4086ce08-f0b3-4667-b790-f84853f0b400.png)
If I later add/remove curves, it add/removes both the line and the quantiles (as expected), although not fixing the other unselected quantiles.
![image](https://user-images.githubusercontent.com/11065596/160949535-367a4abe-5bd1-4ba2-8883-6304f00ef979.png)

**Comment by TomDLT** [comment]
Side question: Wouldn't it be better to have the legend on the side of the plot, instead of below?

**Comment by tanglef** [comment]
Hello,
The quantiles "ghosts" were reported in #301 and there's a proposed fix in #302. I've added a commit in the same PR to take care of the ` dataset_selector` cohesion.
Thanks

**Comment by mathurinm** [comment]
Fixed in #302
