### ISSUE TITLE
It's hard to bench on new dataset

### ISSUE THREAD

**Issue by EugeneNdiaye** [benchopt/benchOpt#32]
it seems quite difficult to launch a benchmark on a new dataset. 

- Adding a file new_data.py by copying boston.py for example does not work

 - It would also be cool to be able to download a local dataset and benchmark on it.

WDYT?

**Comment by TomDLT** [comment]
Did you change the name of the new dataset (e.g. `name = "New_Boston"`) in `new_data.py`?
It seems to work for me.

**Comment by EugeneNdiaye** [comment]
Indeed, it works! My new_data itself was broken :-(

**Comment by mathurinm** [comment]
@EugeneNdiaye could something be made clearer in the doc, that would have helped you? https://benchopt.github.io/how.html#datasets
