### ISSUE TITLE
Possibility to skip a dataset based on some objective parameters

### ISSUE THREAD

**Issue by zaccharieramzi** [benchopt/benchopt#321]
I think I didn't see a way to do this, so I was wondering whether it was possible to skip a dataset altogether depending on some objective parameters.

My usecase is rather simple to explain: a parameter in my objective controls the type of CV DL model to be used. In the case of VGG, it's not possible to have images smaller than 32x32, which is the case for MNIST, so I would like to skip this dataset in this case.

I can try to look into how to implement that if you want.

**Comment by tomMoral** [comment]
It seems a nice feature to add, and not too complicated.
I would say we need to do the same as what we do with the solver: add a method `skip` in the objective and skip when it return `True`.

**Comment by zaccharieramzi** [comment]
But is there a simple way to access the objective's params, rather than the objective dict?
Or would we need to pass the discriminating params in the objective dict?

**Comment by zaccharieramzi** [comment]
Actually in the current framework, it would make more sense to have the objective skip the dataset, rather than the dataset skip the objective.

I am going to rather implement that.

**Comment by tomMoral** [comment]
Yes that would make more sense as the order for the runner is:
- instanciate the dataset
- instanciate the objective and use `_set_dataset`.
- instanciate the solver and use `_set_objective`.

the call to skip shoud be done in `_set_dataset`, as it is done in `Solver.set_objective`.

**Comment by zaccharieramzi** [comment]
Yes I did exactly that! ready to review

**Comment by tomMoral** [comment]
Closed in #323
