### ISSUE TITLE
Finance (and possibly other datasets) issues with zeros columns 

### ISSUE THREAD

**Issue by josephsalmon** [benchopt/benchOpt#35]
When launching benchOpt with the `finance` dataset (for `lasso` or `nnls`) you can get such a warning:

```
lasso/solvers/cd.py", line 46, in run
    L, n_iter)
ZeroDivisionError: division by zero
```
For finance this could be solved by doing the same pre-processing as in `celer`, removing columns with too small norms: https://github.com/mathurinm/celer/blob/dea87fe226450770c3dc3bfe23cf421202221dcf/celer/datasets/libsvm.py#L143

But what should we do in general to handle (the weird case) where one column is a zero vector?
1) hope nobody proposes such a dataset (so raise a warning on the solver page)
2) rewrite the solvers to avoid such an issue?

wdyt @mathurinm @agramfort ?

**Comment by agramfort** [comment]
col should just be skipped on each cd epoch

>
