### ISSUE TITLE
Website scaling for small screens

### ISSUE THREAD

**Issue by TomDLT** [benchopt/benchopt#365]
The title bar is a bit long, so for small-to-medium screens it takes up to 3 lines. Note that the layout is correctly changed for very small screens (e.g. phones).
![image](https://user-images.githubusercontent.com/11065596/167529791-715d5ae8-6ac4-41b7-8388-55c67e116e15.png)
____
Also, the side panel cannot be scrolled, so if the screen is too small we cannot see part of the side panel.
![image](https://user-images.githubusercontent.com/11065596/167530142-11bc0715-ed9e-41bc-a35f-8d79481fad12.png)

**Comment by agramfort** [comment]
on safari when I scroll down on the front page I get this now
<img width="763" alt="Screenshot 2022-05-17 at 09 05 20" src="https://user-images.githubusercontent.com/161052/168750014-8c154154-0116-49e7-bf8b-e8900679a081.png">

it works on chrome though
