### ISSUE TITLE
BUG  benchopt info fails when the safe import context is not named `import_ctx`

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#370]
benchopt info tells me mne is installed, but it is not. Notice I am running directly from the `benchopt_lasso` environment.

```
(benchopt_lasso) ➜  lasso git:(bench) ✗ benchopt info . -d meg         
Info regarding the benchmark 'lasso'
WARNING: astropy not found, will default to scipy for convolution
----------
# DATASETS
----------
## MEG
✓ available in 'running env'
> requirements:
    conda install -c conda-forge mne
----------
(benchopt_lasso) ➜  lasso git:(bench) ✗ ipython
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:22:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import mne
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import mne

ModuleNotFoundError: No module named 'mne'
```

from https://github.com/benchopt/benchmark_lasso/pull/84 (maybe an issue in my MEG Dataset class ?

@tanglef

**Comment by tomMoral** [comment]
yeah, this is a tricky one; the `safe_import_context` needs to be called `import_ctx`.
Not sure how to make this less error prone. One way would be to check if no `import_ctx` exists and if so, check the locals for an instance of the `safe_import_context` class... but not sure it is worth it.

**Comment by mathurinm** [comment]
The solution sounds heavy indeed but I think currently it is not a robust design to rely on the variable name; I feel the generic user is used to calling his contexts with arbitrary names

**Comment by tanglef** [comment]
Can we rename the issue with sth like "safe_import broken when not used with import_ctx" to keep a clearer trace of this for later ?
