### ISSUE TITLE
ENH: allow `stopping_criterion()` to track something different than `value`

### ISSUE THREAD

**Issue by jolars** [benchopt/benchopt#371]
For some benchmarks tracking the primary objective may cause premature convergence with respect to other measures. This is for instance the case in the lasso benchmark where many solvers only make progress on the dual (and duality gap) rather than the primal, but the current implementation causes these solvers to stop.

It would therefore be nice if one could select which objective to track for progress when defining the objective.

@mathurinm proposed that an optional `objective_key` could be passed from `StoppingCriterion()` to determine which objective to check for tracking progress. 

@tomMoral noted that this should probably be defined in the objective to give a centralized way to change this for all the solvers

**Comment by agramfort** [comment]
is it a blocker now?

**Comment by jolars** [comment]
No, it was determined to be low priority.

**Comment by mathurinm** [comment]
Addressed in #461
