### ISSUE TITLE
ENH use pynvml to check conda info

### ISSUE THREAD

**Issue by tomMoral** [benchopt/benchopt#378]
I got several issues on platforms where I have a GPU but no access to `nvcc`, as solvers such as `cuml` relies on the fact that we can find a `nvcc`.
I propose to use `pynvml` to check the GPU info: this will be more robust and this will also allow to access to the name of the GPU, which is more informative (knowing if we have a `V100` or a `Titan`).

**Comment by tanglef** [comment]
I agree (and can look at it now ?) with that !
Also I found out the hard way `nvcc` can have slightly different versions in different conda envs leading to reinstalls for `cuml` depending on the `-e` flag

**Comment by tanglef** [comment]
Would an access not to `nvcc` but to `nvidia-smi` would be okay?
(Technically `pynvml` only mimics the output of `nvidia-smi`....)

**Comment by tomMoral** [comment]
Why not but I think it is easier to user `pynvml` as it has a python interface no?

**Comment by tanglef** [comment]
I can do what pynvml do in Python using 2 lines: subprocess+ regex.
Also pynvml doesn't give the cuda version... Subprocess+regex can
