### ISSUE TITLE
ENH expose BaseDataset to benchmark

### ISSUE THREAD

**Issue by jolars** [benchopt/benchopt#469]
I frequently find myself repeating code for each instance of the `Dataset` class, especially for doing preprocessing of data. I think it would be nice to have an overarching class with methods that can be provided such that they are applied to each dataset. I'm not quite sure how this would work with the design we currently have, however.

**Comment by mathurinm** [comment]
In #472 we will allow for using a module name `benchmark_utils` in which it is possible to define a `TemplateDataset` (or any other name) and then the class can be imported in all datasets, and implemented datasets can inherit from it

**Comment by jolars** [comment]
Sounds great!

**Comment by mathurinm** [comment]
@jolars you can close if #472 filled the need
