### ISSUE TITLE
[RFC] Changing time axis to be something else (iterations/comm. rounds/epochs) in benchopt reporting

### ISSUE THREAD

**Issue by jeandut** [benchopt/benchopt#526]
[User story]
I am a new user of benchopt interested in benchmarking optimizers but my budget is not counted in CPU-time but in iterations/communication rounds/epochs/anything that represent the number of times my solver does a certain operation. Therefore I would like, with minimal changes, to have benchopt automatically produce plots with the sequence of $\theta_t$ being indexed by whatever $t$ I want and optionally modify the name/unit of the x-axis to reflect this change.
Should I:  
1. hack benchopt on my own and potentially do a PR
2. wait for it to be implemented
3. consider using another tool as this use-case isn't and should not be in the scope of benchopt

If 1. where should I begin ?  

Thank you again. It's a great tool !

**Comment by jeandut** [comment]
Note that apparently my question is already solved in one example as citing Appendix C.3 of the article:
```
C.3 Wall-clock time versus number of iterations
Measuring time or iteration are two alternatives that make sense in their respective contexts. Practitioners mostly care about the time it takes to solve their problem, while researchers in mathematical
optimization may want to abstract away the implementation and hardware details and only consider
iteration. The benchmarks we have presented showcase efficient implementations and are also
interested in hardware and implementation differences (e.g. CPU vs GPU solvers for ??, torch versus
tensorflow for Section F.4), hence our focus on time. However, Benchopt does not impose a choice
between the two measures: it is perfectly possible to create plots as a function of the number of
iterations as evidenced for example in ??.
```
However the hyperlink is broken (at least in the arXiv version)

**Comment by mathurinm** [comment]
Hi @jeandut ! [The WIP PR #479](https://github.com/benchopt/benchopt/pull/479) aims at implementing this, your early feedback on it would help to merge it!

**Comment by jeandut** [comment]
I just did ; )

**Comment by jeandut** [comment]
#479 just got merged with the doc improvement this closes this issue !
