### ISSUE TITLE
Parquet files not produced when repeatedly running benchmarks on the same dataset

### ISSUE THREAD

**Issue by jeandut** [benchopt/benchopt#540]
Environment: MacOS + benchopt 1.3.1. 

I am currently investigating exactly what's going on but it seems that when launching multiple solvers runs on the same datasets using:
```
benchopt run --max-runs N -s solver1 -d my_dataset 
benchopt run --max-runs N -s solver2 -d my_dataset 
benchopt run --max-runs N -s solver3 -d my_dataset 
benchopt run --max-runs N -s solver4 -d my_dataset 
benchopt run --max-runs N -s solver5 -d my_dataset 
```
It ends up creating weirdly named files which might lead to not writing corresponding parquet files at all (!)
```
# first run
benchmark_myrepo.html => associated parquet files timestamped exist
# second run 
benchmark_myrepo_..html => no parquet files
benchmark_myrepo_._1.html => no parquet files
benchmark_myrepo_._2.html => no parquet files
benchmark_myrepo_._3.html => no parquet files
```
However parquet files can still be retrieved opening htmls via the browser and clicking on download data.

**Comment by tomMoral** [comment]
Hello, thanks for the report.

If you can retrieve the parquet files, this means that they exist but there name is probably `..parquet` or `._X.parquet`. As they start with a dot, they are hidden files but you will see them if you use `ls -a outputs`.

It seems that something is messing up with  the `--output` parameter, which has this behavior of adding `_X` when a file exists. Most probable is that we have somewhere `--ouput .` Did you configure this parameter somewhere or is this the default behavior?

**Comment by jeandut** [comment]
Yes I added the -o `.` option. It might be just that.

**Comment by jeandut** [comment]
I guess it is me misreading the documentation I thought `--output` was a directory and not a filename.
My bad ! Closing it as it's not a bug more an incorrect use of the software.
