### ISSUE TITLE
``GithubException`` when publishing result to ``benchopt/results``

### ISSUE THREAD

**Issue by Badr-MOUFAD** [benchopt/benchopt#560]
## Description

I'm getting an error when publishing benchmark results to be ``benchopt/results``

<details>
<summary>Click to expend error logs</summary>

```bash
Traceback (most recent call last):
  File "/home/badr-moufad/anaconda3/envs/nnls-env/lib/python3.10/site-packages/benchopt/utils/github.py", line 47, in publish_result_file
    repo.get_branch(branch)
  File "/home/badr-moufad/anaconda3/envs/nnls-env/lib/python3.10/site-packages/github/Repository.py", line 1700, in get_branch
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/badr-moufad/anaconda3/envs/nnls-env/lib/python3.10/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/home/badr-moufad/anaconda3/envs/nnls-env/lib/python3.10/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {"message": "Branch not found", "documentation_url": "https://docs.github.com/rest/branches/branches#get-a-branch"}

During handling of the above exception, another exception occurred:
```
</details>

## Reproduce

Execute on an already-run benchmark repository

```bash
benchopt publish . -t <YOUR_GITHUB_TOKEN>
```

## Solution

After debugging, I find out that the problem is due to confusion between module and class names

https://github.com/benchopt/benchopt/blob/64c658d39169266883103b911f6d99e8c3b3dfb5/benchopt/utils/github.py#L4

Indeed, `GithubException` is both a module and a class. Replacing the above line with

```bash
 from github.GithubException import GithubException 
```

solves the problem.

Can you reproduce the problem? if so, does the suggested fix solve it?

**Comment by mathurinm** [comment]
I'm not sure, because the imported GithubException seems to be the exception class, not the module:
![image](https://github.com/benchopt/benchopt/assets/8993218/aef36f89-f490-42e9-9a41-3643c8a88598)
are you sure the problem is not caused by something else? The traceback you included does not seem to show an issue with a module/exception confusion, it just raises the correct exception, no?

**Comment by tomMoral** [comment]
Yes, the imported `GithubException` is the right one:
https://github.com/PyGithub/PyGithub/blob/master/github/__init__.py#L65

Could you report the full traceback? (the part after `During handling of the above exception, another exception occurred:`)

**Comment by Badr-MOUFAD** [comment]
As weird as I might appear to be, I'm unable to reproduce it myself :bug:
