### ISSUE TITLE
FEAT - change ``get_next`` to a regular method instead of ``staticmethod`

### ISSUE THREAD

**Issue by Badr-MOUFAD** [benchopt/benchopt#564]
## Context

I'm in a situation where I would like to set the ``n_iter`` growth rate depending on
- the actual solver parameters
- the pass-in dataset

For instance, I have a Solver that can be run using either coordinate descent or L-BFGS. However,
L-BFGS requires fewer iterations (~50) compared to coordinate descent (~n_features) to converge.

Therefore, I get either a figure with many juxtaposed points or a figure that drops to the suboptimality in one iteration.

The current design provides the static method ``get_next`` to define how ``n_iter`` is updated.
However, it sets it regardless of the parameters and the dataset.

## Considered alternatives

Currently, I tweak it to get nicely sampled figures. But, it's (almost) impossible when the range size of the dataset is large or the solvers require an excentric number of iterations.

## Suggestion

Could we opt for a design similar to ``Solver.skip``? It is a regular method that has access to all Solver members, and that gets constantly called before ``set_objective``?

@tomMoral, any thoughts?

**Comment by tomMoral** [comment]
I have to say I am not sure why I set it as a `staticmethod` in the first place...
I think this is legacy design from previous iterations in `benchopt` so if removing this makes it work, I am in favor of doing so.

**Comment by Badr-MOUFAD** [comment]
On it!
