### ISSUE TITLE
FEAT access to n_iter in compute 

### ISSUE THREAD

**Issue by JuliaLinhart** [benchopt/benchopt#592]
It would be nice to have access to `n_iter` in the `compute` function. This way we could specify at which iteration a given metric should be computed. For example we want to optimize, i.e. define the `stopping_strategy` w.r.t. `value=metric_1`, but compute `metric_2` only every 10^th iteration (as its computation is more costly).

**Comment by mathurinm** [comment]
With #576 we'll allow passing anything between objective.get_result and solver.compute so this should be possible then!

**Comment by tomMoral** [comment]
Is it good enough for your use case @JuliaLinhart ?
Otherwise, feel free to reopen the issue.
