### ISSUE TITLE
ENH: improve benchopt manual

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#6]
(base) ➜  ~ benchopt -h           
Usage: benchopt [OPTIONS] COMMAND [ARGS]...

  Command-line interface to benchOpt

Options:
  -h, --help  Show this message and exit.

Commands:
  bench  Run benchmark.
  run    Run benchmark.

The difference between the two commands is not very clear only from this info; `benchopt bench -h` and `benchopt run -h` did not help me a lot since the only difference I see is the `recreate` option in one of them.

**Comment by tomMoral** [comment]
The `bench` command have been removed, this should be clearer for now.
Closing this issue.
