### ISSUE TITLE
Shouldn't you have two sequences of variables for the accelerated version?

### ISSUE THREAD

**Issue by gowerrobert** [benchopt/benchOpt#60]
For instance this line only has variables _w_

https://github.com/benchopt/benchOpt/blob/01acb156bd76708b01a30c3de8918609f1cde3ff/benchmarks/lasso/solvers/python_pgd.py#L31

but I think you need two sequences. Something like this (note the additional variables in x)

       L = np.linalg.norm(self.X, ord=2) ** 2
       n_features = self.X.shape[1]
       w = np.zeros(n_features)
       x = np.zeros(n_features)
       t_new = 1

        for _ in range(n_iter):
            if self.use_acceleration:
                t_old = t_new
                t_new = (1 + np.sqrt(1 + 4 * t_old ** 2)) / 2
            grad = self.X.T.dot(self.X.dot(w) - self.y)
            x_old = x.copy()
            x -= grad / L
            x = self.st(x, self.lmbd / L)  # Not sure what this step does
            if self.use_acceleration:
                w = x+ (t_old - 1.) / t_new * (x -x_old)
        self.w = w

**Comment by mathurinm** [comment]
Thanks @gowerrobert ! 
`self.st` is the soft thresholding step
with the code you included, if `use_accel` is False, `w` is always 0 and so `grad = self.X.T.dot(self.X.dot(w) - self.y)` should not be correct, right ?
Also one subtlety is that you need to return `x`, not `w`  (w is most likely dense because it never forgets initial `x`s in its update formula `w = x+ (t_old - 1.) / t_new * (x -x_old)`

I'll give it a more detailed look in the afternoon

**Comment by mathurinm** [comment]
OK so I thought there was a way to do it with a single sequence, but it's not so obvious any more.

Adopting this notation (z accelerated, w point to return):
![image](https://user-images.githubusercontent.com/8993218/92912355-02bd8500-f42a-11ea-8406-9ffb379b2475.png)

I propose this implementation:
```
for _ in range(n_iter):
    if self.use_acceleration:
        t_old = t_new
        t_new = (1 + np.sqrt(1 + 4 * t_old ** 2)) / 2
        w_old = w.copy()
    else:
        z = w
    w -= self.X.T @ (self.X @ z - self.y) / L  
    w = self.st(w, self.lmbd / L)

    if self.use_acceleration:
        z = w + (t_old - 1.) / t_new * (w - w_old)
self.w = w
```

do you agree ?

**Comment by gowerrobert** [comment]
Yes, that looks good to me!
