### ISSUE TITLE
API rename compute/get_result to evaluate_solution/get_solution

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchopt#604]
It would make their connection more obvious, as we did in #460 with to_dict > get_objective

We'll need to change in many repos so not sure it's worth it, but it does sound nicer...

**Comment by mathurinm** [comment]
@francois-rozet what bothers me with `get_solution` is that it's not a solution to the optimization problem. And we're heading for settings in which it's just the result of a method, not a solution. 

What do you think of `get_result/evaluate_result` ?

**Comment by francois-rozet** [comment]
`evaluate_result` is good as well. However, I am not sure to understand why `get_result` does not return a solution. Semantically, a "solver" returns a "solution".

**Comment by mathurinm** [comment]
the way I see it, the solution is $x^* = \\text{argmin} f(x)$ (exactly). Solvers only output an estimate of the solution -- all the more when run with low n_iter or high tol.

If the benchmark is not even an optimization problem, like the comparison of sparse recovery methods of @TheoGuyard, and you use a solver like OMP which does not solve an optimization problem, then it's not super what "solution" would refer too.

**Comment by tomMoral** [comment]
Yes this could be a sub-optimal solution.
But I am more in favor of `result`, as this is less specific to optimization than `solution`.

**Comment by agramfort** [comment]
We call it solver so it returns a solution 

Lets not change things for cosmetic reasons.

**Comment by mathurinm** [comment]
several people stated that it was confusing during the sprint, especially compared to get/set_dataset and get/set_objective
IMO it's not too late to change and makes onboarding easier, as #588

**Comment by tomMoral** [comment]
This is not only cosmetic, this helps with documentation and API consistency (many said during the sprint that this was a confusing point). Thus we would like to change `compute` to match the `get_result` method. The question is what it the right wording. We also want to consider the `get_one_solution` that is going to enter this function and the name of the object passed in the `callback`, to make all of this consistent.

- `solution` is more natural with `Solver`, but refers to optimization and hurts the semantic of @mathurinm  :laughing: 
- `results` is more general (thinking of ML benchmarks), and the nice thing is we don't change `get_result`.
 
I am in favor of this solution with: `get_result/get_one_result/evaluate_result/callback(**result)`. This will be more consistent.
What do you think @mathurinm , @agramfort , @francois-rozet

**Comment by agramfort** [comment]
I will not fight against this. I just say that API changes are not free
(deprecation, code breakage etc.)
Also over the years I've seen many examples of people arguing that your API
is not logic but if you change
everytime someone comes with his own prior it's a pure random walk. If you
want API changes just make sure
it's what is best for the majority, not just the last person arguing about
it.

**Comment by francois-rozet** [comment]
Both solution and result are fine to me, with a preference for solution to be consistent with  Solver (btw a sub-optimal solution remains a solution, same for intermediate solution). The real improvement is changing `compute` to `evaluate_solution` or `evaluate_result`.

**Comment by tomMoral** [comment]
The automated call to `get_result` is indeed a nice improvement that could be made as the same time, as well as letting `evaluate_result` take an expanded dictionary as input.
