### ISSUE TITLE
CLI ImportError: cannot import name '__version__' from 'benchopt' (unknown location)

### ISSUE THREAD

**Issue by paquiteau** [benchopt/benchopt#608]
Hi, I am trying to install benchopt as an editable package in an (pyenv managed) virtualenv with 

``` shell
git clone https://github.com/benchopt/benchopt
cd benchopt
pip install -e .
```

The install succeed, but when I try to run the benchopt cli I get the following error:
```
Traceback (most recent call last):
  File "/home/pac/.pyenv/versions/benchopt/bin/benchopt", line 5, in <module>
    from benchopt.cli import benchopt
  File "/home/pac/gits/nsp/benchopt/benchopt/benchopt/cli/__init__.py", line 3, in <module>
    from benchopt import __version__
ImportError: cannot import name '__version__' from 'benchopt' (unknown location)
```

I am running python 3.10.9 and pip 23.1.2 . 

Note that  after installation I can still do

```python
>>> import benchopt
>>> from benchopt.__version__
>>> benchopt.__version__
'1.4.1.dev4'
```

This is unlikely an isssue with pyenv, as I have other packages with CLI that work just fine (See https://github.com/paquiteau/brainweb-dl for a working example)

**Comment by mathurinm** [comment]
I can't reproduce inside a freshly created virtualenv, everything works fine. Can you provide then benchopt command that leads to the error ? IIRC it was a standard benchopt run ?

**Comment by paquiteau** [comment]
A simple `benchopt --version` or `benchopt version` would trigger the error for me.

**Comment by Badr-MOUFAD** [comment]
Me neither, I can't reproduce the error.

As reported, I run

```bash
# clone/cd to benchopt
git clone https://github.com/benchopt/benchopt.git
cd benchopt

# create/activate new virtual env
python3 -m venv venv
source venv/bin/activate

# install in editable mode
pip install -e .

benchopt --version
# OUT: 1.4.1.dev5
```

Can you try upgrading setuptools? you can run
```bash
python3 -m pip install --upgrade setuptools
```
