### ISSUE TITLE
Instantiation of `NoCriterion` fails

### ISSUE THREAD

**Issue by maltezfaria** [benchopt/benchopt#615]
Is this expected?

```python
>>> from benchopt.stopping_criterion import NoCriterion
>>> NoCriterion()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/pkgbuild/lib/python3.11/site-packages/benchopt/stopping_criterion.py", line 67, in __init__
    assert strategy in STOPPING_STRATEGIES, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: strategy should be in ['iteration', 'tolerance', 'callback']. Got 'None'.
```

I want to control the stopping criterion manually, using `max_iter`, so I tried setting my solver's `stopping_criterion` to `NoCriterion`, and got an error.

**Comment by mathurinm** [comment]
Not sure, but this may be legacy code : it's not used in the benchopt repo.

What do you mean by, "I want to control the stopping criterion manually, using max_iter" ? isn't `sampling_strategy = "iteration"` enough ? if you want a finer control on the sequence of `max_iter` used by your solver, you can control it via the `get_next` method (see en of this paragraph : https://benchopt.github.io/performance_curves.html?highlight=how%20sampling%20curves#using-iterations-or-tolerance)

Or do you want a single run ? In the case `SingleRunCriterion` would be the way to go.

**Comment by maltezfaria** [comment]
You are right, I don't really need it: `get_next` does what I want. Thanks!

**Comment by maltezfaria** [comment]
This bug is related to legacy functionality no longer used in `benchopt`, closing the issue.
