### ISSUE TITLE
BUG minimum version required

### ISSUE THREAD

**Issue by TimotheeMathieu** [benchopt/benchopt#661]
Hello,

I am trying to follow the tutorial to try and use benchopt and I did the test on two benchmarks (benchmark_lasso  and benchmark_logreg_l2) but none of them worked because the required version of benchopt for these two benchmark is not yet released. I get the following error:

```
RuntimeError: benchopt version 1.4.1.dev36 is too old to run this  benchmark, version 1.5 is required. Please update benchopt with `pip install -U benchopt` for this benchmark.
```

There seems to be a bug somewhere because version 1.5 is (from what I saw) not out yet.

**Comment by tomMoral** [comment]
I just triggered the release of `benchopt` 1.5, it should lend on `pypi` in about 30min :)

**Comment by TimotheeMathieu** [comment]
Ah ok, just a "right place wrong time" phenomenon then. 
Thanks, will try again this afternoon.

**Comment by tomMoral** [comment]
It has just been released :)

https://pypi.org/project/benchopt/

**Comment by TimotheeMathieu** [comment]
Yes thanks, it is working fine now everything seems to work out of the box.
