### ISSUE TITLE
ENH: benchopt must be run from the repo folder

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#7]
However there is a benchopt alias defined, and running it from another folder either gives no output - if no benchmark is specified : 
```
(base) ➜  ~ benchopt bench --max-samples 5 -n 10  -s blitz 
(base) ➜  ~ 
```
(no figures generated)
either fails :
```
(base) ➜  ~ benchopt bench --max-samples 5 -n 10 logreg -s blitz
...
AssertionError: {'logreg'} is not a valid benchmark. Should be one of: []
```

**Comment by tomMoral** [comment]
Now `BENCHMARK` argument is mandatory and  0b75e62 raise a better explaination.
I am closing this issue.
