### ISSUE TITLE
Out of date documentation: callback

### ISSUE THREAD

**Issue by tobias-liaudat** [benchopt/benchopt#724]
The documentation of the callback argument is out of date, see [here](https://benchopt.github.io/performance_curves.html#using-iterations-or-tolerance)

For example:

`while callback(x):` should be `while callback():`

**Comment by vloison** [comment]
The link is a pointer to version 1.4.1 . The documentation of version 1.5.2 seems up to date. To avoid this, one could remove links to older doc.

**Comment by mathurinm** [comment]
Thanks for raising this, this is part of a more general issue : the documentation features pages from older versions of the doc. See https://github.com/benchopt/benchopt.github.io/issues/2

**Comment by tobias-liaudat** [comment]
@mathurinm ah yes, that's indeed the issue. Thanks!

**Comment by mathurinm** [comment]
The page https://benchopt.github.io/performance_curves.html#using-iterations-or-tolerance is no longer showing!
