### ISSUE TITLE
[ERR] Using ```sample_strategy = run_once```  in a solver fails despite being possible according to the doc

### ISSUE THREAD

**Issue by ambroiseodt** [benchopt/benchopt#733]
In a solver file like solvers/test_solver.py, defining ```sampling_strategy = run_once``` fails with error 
``` AssertionError: sampling_strategy should be in ['iteration', 'tolerance', 'callback']. Got 'run_once'. ```

The issue is that according to the doc, it should be possible, see https://github.com/benchopt/benchopt/blob/2f85575b5ae34bb30ccafbbbd098bcd8d6aa8ab0/benchopt/base.py#L57C39-L57C47 line 54-59.

To reproduce the issue, define a solver with ```sampling_strategy = run_once``` before the methods as
```
class Solver(BaseSolver):

    name = "test_solver"
    sampling_strategy = "run_once"

    # List of packages needed to run the solver. See the corresponding
    # section in objective.py
    install_cmd = "conda"
    requirements = ["sklearn"]

    def set_objective(self, X, y):
        ...
```

**Comment by tomMoral** [comment]
What is your version of `benchopt`?

**Comment by ambroiseodt** [comment]
benchopt 1.5.1

Replacing ```sampling_strategy = run_once``` by ``` stopping_criterion = SingleRunCriterion()``` works (thanks @mathurinm) but even in the doc there is an issue I think.

**Comment by tomMoral** [comment]
It is because we did not release and it's in the dev version.
The doc reflect the dev version, which is the real problem ^^

**Comment by ambroiseodt** [comment]
Ok, noted thanks
