### ISSUE TITLE
Error: verbose command line argument not recognized

### ISSUE THREAD

**Issue by LeoGrin** [benchopt/benchopt#737]
The [doc](https://benchopt.github.io/user_guide/CLI_ref.html#cmdoption-benchopt-info-v) mentions the verbose option but running:
```
benchopt run . --verbose
```
gives
```
Error: No such option: --verbose
```

Same thing for `-v`

**Comment by mathurinm** [comment]
This may be confusing but the section of the doc you are referring to is for the `benchopt info` command : https://benchopt.github.io/user_guide/CLI_ref.html#benchopt-info

**Comment by LeoGrin** [comment]
oops yeah sorry
