### ISSUE TITLE
ENH change the y lims in the figures so that it scales automatically

### ISSUE THREAD

**Issue by pierreablin** [benchopt/benchOpt#81]
Sometimes you might want to monitor an objective that is different that the function optimized by the solver (eg the error between the predicted coefficients and true coefficients when doing linear regression), and in these cases the value of the objective might not get as close as 10^-9 to the optimal objective. In this case, having an ylim go to 10^-9 makes the plot rather unreadable.

**Comment by agramfort** [comment]
yes plotting functions are quite basic.

either we improve them and make them more automagic or we teach how to make
your own plot.

The latter seems better (less work, and more future proof)

>

**Comment by tomMoral** [comment]
There is no multiple plots, so I guess we can close this one.
