### ISSUE TITLE
[ENH] Add coordinate descent and FISTA solvers for Lasso/Logreg

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchOpt#9]
CD for Lasso: #8

**Comment by tomMoral** [comment]
Not sure if we still want to implement FISTA?
WDYT @mathurinm ?

**Comment by agramfort** [comment]
as long as it does not slow down test suite (too much) I would say yes

**Comment by mathurinm** [comment]
Give me 30 minutes when my ICML reviews are done! :) 
It could even be a parameter of Baseline, since a large portion of the code is shared ?

**Comment by tomMoral** [comment]
Yes I would go for a baseline parameter.
